services:
  - type: web
    name: ladopro
    env: python
    plan: free
    buildCommand: "python show_files.py"
    startCommand: "gunicorn inventario_lab.wsgi:application --bind 0.0.0.0:$PORT"
    autoDeploy: true
