services:
  - type: web
    name: ladopro
    env: python
    plan: free
    startCommand: >
      python manage.py collectstatic --noinput &&
      gunicorn inventario_lab.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
