services:
  - type: web
    name: ladopro
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py collectstatic --noinput && gunicorn inventario_lab.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
